name: 'Deploy Laravel project'
description: 'Execute composer & init database migrate'
author: Viet Vu'
runs: |
  php -r "file_exists('.env') || copy('.env.example', '.env');"
  composer install --no-ansi --no-scripts --no-progress --prefer-dist
  php artisan key:generate
  chmod -R 777 storage bootstrap/cache
  php artisan config:clear
  php artisan migrate:fresh
